// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awhkznqjyaualtbrheoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aGt6bnFqeWF1YWx0YnJoZW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQ5MjYsImV4cCI6MjA2NjI4MDkyNn0.not6c_3-sFuKqcVdLMbJW4mVFYbcmiryC4U-gbIrSw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);